name: app

type: 'nodejs:18'

dependencies:
  nodejs:
    yarn: "*"

mounts:
  'web/uploads':
    source: local
    source_path: uploads

disk: 2048

hooks:
  build: |
    npm run buildc

web:
  commands:
    start: node index.js
